### ISSUE TITLE
Can't add more than one ISY Scene?

### ISSUE THREAD

**Issue by ficklma1** [rodtoll/homebridge-isy-js#10]
I've tried to add more than one ISY scenes doing the following
.....
            "includeAllScenes": false,
            "includedScenes": [
                "27346",
                "43224"
            ],
.......

But no matter what, it does not work with multiple entries.  I have to remove the , and second entry.  I've successfully tried many single entries and all work fine, so I know it's not an issue with the names being the same, etc.

Is anyone else able to do multiple scenes?

Thanks

**Comment by ficklma1** [comment]
Has anyone else experienced this?

**Comment by rodtoll** [comment]
I haven't, but my regression test only works with a single scene. It's possible a recent update broke this. I'll have a look tonight.

**Comment by rodtoll** [comment]
Confirmed. There was a bug in the code which picked which scenes to return. It only worked when there was only one scene in your list of supported scenes. Just goes to show you that you get what you test -- and I only tested the case with one scene.

I've fixed it and pushed a new version to npm. V0.0.9 should have the fix.
