### ISSUE TITLE
ISY Insteon Scenes - Status issue / incorrect behavior?

### ISSUE THREAD

**Issue by ficklma1** [rodtoll/homebridge-isy-js#11]
I've noticed that if just one light in a scene is on or (>1%) then homebridge thinks the scene is already on and therefore doesn't really turn the scene on.  Siri states that the scene is turned on, but it actually doesn't trigger the scene within the ISY.  However, If I make sure all lights within the scene are truly showing "Off" then it works fine.

Is anyone else noticing this behavior?

**Comment by rodtoll** [comment]
Yes, this is definitely a bug. A scene pretends to be a light that is not
dimmable, so if it thinks it is on already it won't send a command. And the
definition of on is if the dim level > 0 on any of the individual lights.
Hence this behavior.

Seems like I should just bite the bullet and make a scene act like a
dimmable light as it has been discussed on some other threads.. Then
sending an on command should make all the lights go to 100%. To make this
work I'll need to update isy-js first and then this.

I'll add the fix to my work queue. Thank you for reporting.

**Comment by rodtoll** [comment]
First part of the fix is into the isy-js library. Added a new function to check to see if all devices are matching desired state. Will add to the homekit plugin next.

**Comment by ficklma1** [comment]
Thanks so much!  You rock!

**Comment by rodtoll** [comment]
@ficklma1 - Version 0.1.0 addresses this issue. Scenes now are not considered on until all the devices are on. So if your scene is partially on you can turn it on. If it's partially off though you won't be able to execute an off command. Given light accessories can be either on or off needed to make a choice to optimize for either always being able to turn off for partial scenes or always being able to turn on. Give it a whirl.
