### ISSUE TITLE
devices not ignored

### ISSUE THREAD

**Issue by hmatos-rogers** [rodtoll/homebridge-isy-js#12]
I've added many device strings to the ignore list, but they appear to still be included in the devices passed to homekit.  This is causing an issue where I'm passing more than 100 devices.  Is this a known issue?  I also can't seem to find the DEBUG output for isy-js (even after setting the flag to true).

Here's a snipped from config.json

```
            {
                    "nameContains": "Kitchen:B:Deck"
            }
```

And snippet from output of homebridge command:

[isy-js] Initializing platform accessory 'Kitchen:B:Deck'...

Any help would be appreciated,

Thanks!

**Comment by rodtoll** [comment]
Hi @hmatos-rogers -- 

The issue with your entry above is it only contains the nameContains element. You also need a lastAddressDigit and an address field to be specified as empty strings. Without specifying all three fields the line will be ignored as invalid. 

So the entry should be: 

 {
     "nameContains": "Kitchen:B:Deck",
     "lastAddressDigit": "", 
     "address": ""
}

That should resolve your issue.

For future reference, turning on debugging is specified by setting the debugLoggingEnabled field to true. So for example, add this line to the isy-js config section:

"debugLoggingEnabled": true,

Here's an example config:

```
 "platforms": [
    {
        "platform": "isy-js",
        "name": "isy-js",         
        "host": "10.0.1.12",      
        "username": "admin",      
        "password": "password",   
        "elkEnabled": true,       
        "useHttps": false,
        "debugLoggingEnabled": true,
        "includeAllScenes": false,
        "includedScenes": [
            "27346"
        ],
        "ignoreDevices": [        
            { "nameContains": "ApplianceLinc", "lastAddressDigit": "", "address": ""},
            { "nameContains": "Bedroom.Side Gate", "lastAddressDigit": "", "address": ""},
            { "nameContains": "Remote", "lastAddressDigit": "", "address": "" },    
            { "nameContains": "Keypad", "lastAddressDigit": "2", "address": "" },
        ]
    }
 ]
```

**Comment by hmatos-rogers** [comment]
Thank you very much - the issue is fixed.

**Comment by rodtoll** [comment]
No problem. Enjoy the software.
