### ISSUE TITLE
Devices Turn On but Not Off

### ISSUE THREAD

**Issue by amilham** [rodtoll/homebridge-isy-js#14]
For some reason, I can turn Insteon devices on with this bridge (and set brightness levels), but turning them off never works, even though HomeKit reports the device off.

**Comment by rodtoll** [comment]
Hi @amilham - Turn on debugging and get the system into a state where turning the light on and off don't work and send me the debug output from the console. Then I can look to determine what is going wrong. It should be able to turn on and off -- seems likely that for some reason the local copy of the state of the device didn't update when you switched it so the library thinks the turning off is not needed -- which would point to a bug. 

Some additional questions:
1. What version of the ISY firmware are you running? Is it the latest stable?
2. If you leave it running for about 10 minutes or so does it start working? Or is it start out working and then fail?

**Comment by rodtoll** [comment]
Closing until we get another repro or @amilham provides more data. Happy to continue troubleshooting if you're still up for it @amilham.

**Comment by ZManInNY** [comment]
I have this exact same issue.  I don't think it occurred until I turned on 2-factor auth on my Apple ID so I could integrate my Apple TV with HomeKit.

I can seemingly always turn my Insteon devices on with my iPhone via Homebridge installed on my Raspberry Pi, but I cannot turn them off.  My Insteon Bulb will let me change the brightness several times and then also gives up.  After trying to turn devices off, Homebridge reports the device being off on my iPhone, sometimes with a progress wheel.

Also, if I turn a device on, close control center and re-open control center, the status of the devices refresh and the one I just turned on thinks it's off.  Clearly it's not getting the state information correctly.  If I switch to MobiLync and change the state of a device and then switch back to Homebridge, I can again toggle the device on.  This also works if the device is already on - I can turn it off with Homebridge, but then not on again.  The same fix also applies - change state with MobiLync.

I am using an ISY-994 running the latest stable release, 4.5.1 (6/15/2016).
There is no difference if it just starts up and I test or it's running for 10 minutes or days.

I can't seem to get "debugLoggingEnabled" working properly.  I've set it to true and both restarted homebridge and my Raspberry Pi also, but nothing outputs to the console.

I'm running Node v6.0.0.

Let me know how I can provide more information.

**Comment by respectTheCode** [comment]
There is a bug in the API in one of the ISY versions. Updating the ISY firmware fixed this for me.

**Comment by ZManInNY** [comment]
Hi @respectTheCode. Can you confirm the version of ISY that was problematic and/or the version you upgraded to?  I'm already on the most recent stable release.

**Comment by respectTheCode** [comment]
I am on 4.4.6 now. I don't know what version i was on when I was having this problem.

**Comment by ZManInNY** [comment]
@rodtoll Can you help me get debugging working?
