### ISSUE TITLE
GoControl WS15Z-1 Not Detected

### ISSUE THREAD

**Issue by PhiltorX** [rodtoll/homebridge-isy-js#18]
I installed a GoControl WS15Z-1 Z-Wave on/off switch (not a dimmer) and it's not being detected by homebridge-isy-js. I tried making a scene for it but it won't respond to any on/off commands.Is there any way that support can be added?

**Comment by rodtoll** [comment]
Unfortunately Z-Wave devices need to be added one by one to the underlying isy-js library. They don't have a generic set of type definitions exposed through ISY which allows me to identify the device type. 

You can add support yourself by adding it to the isy-js device list. Go into the homebridge-isy-js/node_modules/isy-js directory and edit the file isydevicetypes.json file. You need to add a new line which tells isy-js how to recognize the device as an on/off switch.

You should be able to take this line:
  { "type": "4.16.1.0", "address": "", "name": "ZW002_1 - On/Off Power Switch", "deviceType": "Light", "connectionType": "ZWave", "batteryOperated": false },

And replace the type entry and the name entry. The name entry should be the friendly name you want for the type. GoControl WS15Z-1 for example.

The type entry you can get from your isy. Go to chrome and visit http://<your isy address>/rest/nodes and find the node entry in the XML which belongs to the above device. Find the type field and use that value in your new entry.

So, if your entry looked like this: 

```
<node flag="128">
<address>ZW005_1</address>
<name>Deck Door Lock</name>
<family>4</family>
<parent type="3">42035</parent>
<type>4.64.3.0</type>
<enabled>true</enabled>
<deviceClass>0</deviceClass>
<wattage>0</wattage>
<dcPeriod>0</dcPeriod>
<pnode>ZW005_1</pnode>
<sgid>1</sgid>
<devtype>
<gen>4.64.3</gen>
<mfg>297.2.0</mfg>
<cat>111</cat>
<model>5</model>
</devtype>
<property id="ST" value="100" formatted="Locked" uom="11"/>
</node>

```

Then you would set the new line in isydevicetypes.json to be:

  { "type": "4.64.3.0", "address": "", "name": "GoControl WS15Z-1", "deviceType": "Light", "connectionType": "ZWave", "batteryOperated": false },

(Yours of course will be different)

If your entry is correct then restarting homebridge should enable the device to show up. 

Assuming that works and you can send me the line you added to isydevicetypes.json and I'll make sure it makes it into a future version of isy-js so you won't need to add it manually in the future. (And neither will others).

**Comment by PhiltorX** [comment]
Great! I'll give it a try. If I can get it to work I will I'll provide you with the info. Thanks.

**Comment by PhiltorX** [comment]
It works! Here's the line I added:
{ "type": "4.16.3.0", "address": "", "name": "GoControl WS15Z-1 On/Off Power Scene Switch", "deviceType": "Light", "connectionType": "ZWave", "batteryOperated": false }

**Comment by rodtoll** [comment]
Excellent news. I'll put this in my worklist for the next version of isy-js. Thanks for sending the information!
