### ISSUE TITLE
Scenes not appearing unless includeAllScenes is set to true

### ISSUE THREAD

**Issue by Chioti** [rodtoll/homebridge-isy-js#20]
It used to work but I no longer get any scenes.

**Comment by rodtoll** [comment]
I'm unable to reproduce this locally. I have reset my homeconfig, setup homebridge and homebridge-isy-js on a whole new machine and copied my config which has includeAllScenes set to false. All my scenes still show up. 

Are there any errors appearing locally? Are the scenes listed in the initial startup? Could this be a side effect from one of the failures you were seeing? (Socket resets on startup?)

=== For reference, if we can't get them back any other way ===

Worse case I would reset and start from scratch. Just note that this will destroy all of your setup -- rooms, zones, triggers, etc. 
1. Shut down homebridge.
2. Go to your .homebridge directory and delete your persist directory.
3. Close down any Homekit apps you have.
4. Go to your iphone/ios device into settings into settings > privacy > homekit > reset homekit configuration.
5. Restart homebridge.
6. Add homebridge back to your homekit.

**Comment by Chioti** [comment]
@rodtoll This was a config issue.  I used the scene name instead of the scene number.  Once I changed it to the scene number the scene (and it's name) appear in homekit.

**Comment by rodtoll** [comment]
Happy to hear it is working for you.
