### ISSUE TITLE
Anyway to change what Siri says after command?

### ISSUE THREAD

**Issue by psmith3** [rodtoll/homebridge-isy-js#22]
Most of my device names are plural (lights & doors) and I am wondering if it is possible to change the phrase that Siri says after a state change. For example, when I say, "turn on the floodlights", Siri says "the floodlights is on." Is it possible to change Siri to say, "the floodlights are on"? I've looked around inside the files and cannot find where Siri is told how to respond. Is that in the plugin or is that native to Siri?

**Comment by rodtoll** [comment]
@TheHavocHero - Unfortunately it is native to Siri and we can't change it.
