### ISSUE TITLE
Feature request: Add ISY Programs as devices

### ISSUE THREAD

**Issue by psmith3** [rodtoll/homebridge-isy-js#23]
Is there any plans to add Programs to the items that can be controlled?

**Comment by rodtoll** [comment]
Yes, although there is not a good fit for them in terms of device types I have just struggled with the right representation in HomeBridge. A program is kindof like a momentary button or a push button which are both devices types in HomeKit but HomeBridge apps don't seem to support them.

I was thinking of allowing you to specify the programs you would like exposed and whether turning them on would cause them to run the if, the true path or the false path. Once that is set they would appear as switches. Would that work for your use case?

**Comment by psmith3** [comment]
UDI just added the ability for Amazon Echo to be able to run programs on the ISY controller. "Using Connected Home API, you can also control ISY programs: Alaxa, turn on/off <program name>. On: runs the If. Off: runs the Else."

Might be the best way to follow. Thank you for implementing this.

**Comment by innovatorgit** [comment]
Yeah that would work great for me too

**Comment by respectTheCode** [comment]
With home assistant you can run programs but they approach it from a different direction. Instead of trying to make a generic program work they allow you to create virtual devices with programs.

https://home-assistant.io/components/isy994/#creating-custom-devices

**Comment by rodtoll** [comment]
Closing all feature requests as part of discontinuing support.

**Comment by ZManInNY** [comment]
Why has this been discontinued?  ISY still doesn't (and probably never will) have HomeKit integration.

**Comment by PaulWieland** [comment]
The developer simply didn't have time to work on it any more.
UDI is working on something called [polyglot](https://github.com/UniversalDevicesInc/polyglot-v2) which essentially gives the ISY a better API for integrating stuff with it. Unfortunately its rather has overly complex requirements for backend (in my opinion).

However by combining Polyglot + [Homebridge-MQTT](https://github.com/cflurin/homebridge-mqtt) I think we could get away from ISYJS. I haven't made that leap yet mind you, but I am using Homebridge-MQTT for other purposes and it works really well.

All we need is a bridge between the ISY and MQTT (which Polyglot is supposed to support) and then HomeKit will work just fine.
