### ISSUE TITLE
Is there a procedure somewhere for how to add or change accessories to an existing homekit database?

### ISSUE THREAD

**Issue by PaulWieland** [rodtoll/homebridge-isy-js#28]
I add or change stuff to my Insteon network or in my ISY. Is there a procedure for getting these changes (or new devices) to show up in homekit without having to delete the homekit database and persist folder in homebridge? So far that's the only way I've been able to get new devices to show up, but it means recreating all of my rooms from scratch.

**Comment by rodtoll** [comment]
New devices should show up -- at least they used to. The one case where it
won't is if you exceed the maximum device count. Are you close to the
maximum? I've seen once you exceed the maximum event once in a setup things
get wonky until you do the rest as you describe below.

If not, then it's a homebridge issue and we'll need to seek assistance from
the main project.

**Comment by ghost** [comment]
Upgraded and can no longer connect.  Reset my Homekit from inside IOS and deleted the persist db, restart homebridge, but nothing.  Homebridge shows it's ready, but device never connects when I try to add accessory.

**Comment by PaulWieland** [comment]
It seems like maybe this was an issue with an older version. I just upgraded everything (homebridge and the isy plugin) and did some testing and it works as expected.
