### ISSUE TITLE
  Garage Door Issues

### ISSUE THREAD

**Issue by macjeff** [rodtoll/homebridge-isy-js#29]
I have 3 garage doors.  I will paste the code below but Garage 2 and 3 are naming fine but the first one is not.   I tried reordering it, changing names, deleting all devices and re-adding.  Nothing but 2 and 3 woe great.  Device 15 18 05 is the issue.  I triple checked the device ID and even tried it like 15.18.05.1    No luck.  HELP!!!

Everything else is working great.  I just have about 600 devices so i had to do a lot of filtering!!!

"garageDoors": [ {
"address": "15 18 05 1",
"name": "Tucker's Garage",
"timeToOpen": 12000
},{
"address": "15 16 A5 1",
"name": "Casey's Garage",
"timeToOpen": 12000
}, {
"address": "15 17 2D 1",
"name": "Jeff's Garage",
"timeToOpen": 12000
}
],

**Comment by rodtoll** [comment]
Completely understand. The 100 device limit is very challenging in big installations. I have about 200 myself. 

Unfortunately the way garage doors are treated by homebridge and homekit there is often an issue where only a subset of the garage doors will work. I've been unable to find anything to indicate a bug in the plugin -- the devices are being exported correctly. But control isn't working.

Leaving it open in case someone else has more symptoms.
