### ISSUE TITLE
Device type and icons in iOS 10 Home app

### ISSUE THREAD

**Issue by psmith3** [rodtoll/homebridge-isy-js#33]
Any idea if there is a way to set the device type for the insteon accessories so that the icon can be changed in the iOS 10 Home app? In the new app for example, I would like to be able to designate my 240v Load Controllers to something other than a light as the app reports that it is a light when it actually is a Pool Pump. I also would like a on/off module to show a heater instead of a switch. Not sure if this is possible.

**Comment by rodtoll** [comment]
At the moment there is no way to do this. I would need to enable users to override device type identification for specific devices. I will add to the feature request backlog.
