### ISSUE TITLE
Am I the only one with port issue?

### ISSUE THREAD

**Issue by nawaidrana** [rodtoll/homebridge-isy-js#35]
My insteon hub runs on port 25105. When I put everything as documented in my config.json, and start homebridge, it doesnt do anything for a minute or so and then throw a timeout error, and I can see from log that it is trying to connect to my insteon hub at port 80 instead of port 25105. 

When I run this in my browser, my garage door opens, but it seems like isy-js is not looking at this port?

"http://admin:password123@10.0.1.12:25105/3?0262348H7D0F12ff=I=3

Any advice or feedback will be appreciated.

**Comment by nawaidrana** [comment]
and BTW, this is my json.config (I have a nest platform, this is the second one in my config file)

{
           "platform": "isy-js",
           "name": "isy-js",
           "host": "10.0.1.12",
           "username": "admin",
           "password": "password123",
           "elkEnabled": false,
           "useHttps": false,
           "debugLoggingEnabled": false,
           "includeAllScenes": false,
           "includedScenes": [
                "27346"
            ],
           "garageDoors": [
               { "address": "348H7D", "name": "Garage Test", "timeToOpen": 12000 }
           ]
 }

**Comment by nawaidrana** [comment]
Sorry for multiple comments, but here is the log that I see when I run homebridge:

[Fri Sep 30 2016 14:58:58 GMT-0700 (PDT)] Loading 2 platforms...
[Fri Sep 30 2016 14:58:58 GMT-0700 (PDT)] Initializing Nest platform...
[Fri Sep 30 2016 14:58:58 GMT-0700 (PDT)] Fetching Nest devices.
[Fri Sep 30 2016 14:58:58 GMT-0700 (PDT)] [isy-js] Initializing isy-js platform...
..
.. (loads garage door accesorry using my legacy accesory script)
.. correctly connects to nest to get temperatures .. etc.

...
/usr/lib/node_modules/homebridge-isy-js/node_modules/isy-js/isy.js:542
        throw new Error("Error calling ISY"+err);
        ^

Error: Error calling ISYError: connect ETIMEDOUT 10.0.1.12:80
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-isy-js/node_modules/isy-js/isy.js:542:15)
    at emitTwo (events.js:92:20)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireError (/usr/lib/node_modules/homebridge-isy-js/node_modules/restler/lib/restler.js:206:10)
    at ClientRequest.<anonymous> (/usr/lib/node_modules/homebridge-isy-js/node_modules/restler/lib/restler.js:246:14)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:259:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1253:8)
    at doNTCallback2 (node.js:439:9)
    at process._tickCallback (node.js:353:17)

**Comment by respectTheCode** [comment]
This module requires an ISY and does not work with the insteon hub.

http://www.smarthome.com/isy994izw-insteon-z-wave-controller-with-dual-band-plm.html

**Comment by nawaidrana** [comment]
Thank you very much! I don't know if I should be spending $300 for another hub. Is there an Insteon hub capable homebridge script? I am currently using a legacy script, but it doesnt correctly tell me the state that my garage door sensor (io-linc) is in (in addition to I have to tell Siri to turn "on" the garage rather than open).

**Comment by rodtoll** [comment]
Not that I am aware of. The Insteon Hub uses a different API so someone would need to write a plugin for it directly.
