### ISSUE TITLE
Identification request kills homebridge

### ISSUE THREAD

**Issue by suderman** [rodtoll/homebridge-isy-js#37]
Tapping identify on any lightbulb device will kill the homebridge process. This is particularly painful when adding a whole Insteon network when first getting started. This doesn't seem to be a problem for switch devices. 

https://imgur.com/gallery/QxCVg

By the way, this plugin and isy-js are amazing projects. Thanks for sharing your work!

**Comment by rodtoll** [comment]
Thanks for identifying this and submitting a pull request. I'll incorporate this fix in my next release.

**Comment by rodtoll** [comment]
Resolved in plugin 0.1.6 just published to npm.
