### ISSUE TITLE
Issue with Insteon+ app + homebridge-isy-js

### ISSUE THREAD

**Issue by PaulWieland** [rodtoll/homebridge-isy-js#4]
I'm usining the Free Insteon+ iOS app from the app store in order to pair my phone with homebridge. It paired successfully.

The Siri commands seem to work fine so I do not know if this is a bug with the insteon app or the homebridge ISY plugin. Apologies if this isn't the right place to report this!

The problem: 
I have an ISY994i. When using the Insteon+ app GUI to turn the light off, the ISY receives an off command immediately followed up by an on command (confirmed by watching the event log on the ISY Admin console).

Note that when sending commands via Siri it seems to work okay.

**Comment by rodtoll** [comment]
I loaded up the Insteon+ application and was able to reproduce your issue. So it's not your setup. There is an issue somewhere. 

I tried Beam, Home -Smart Automation and MyTouchHome which are all HomeKit applications and they did not reproduce the issue. Seems like this is an Insteon+ specific issue so it is likely something on their end. I would recommend reporting a bug to them.

**Comment by rodtoll** [comment]
Btw, I read through the reviews on the Insteon+ app and you are not the only one seeing issues. Hopefully they will address them with an update. In the meantime Siri should work and you could always use another HomeKit app.

**Comment by PaulWieland** [comment]
Hi @rodtoll I really should have read the reviews on the app store before submitting this, I would have seen right away that this isn't a homebridge issue. Sorry for the false alarm! Thanks for the speedy response!
