### ISSUE TITLE
Feature Request: Change HomeKit Device Type

### ISSUE THREAD

**Issue by VeniceNerd** [rodtoll/homebridge-isy-js#45]
Hey @rodtoll now that I have ISY-JS up and running I am learning the true power of it. It's an incredible plugin. Thank you so much for providing and updating it. You've achieved what Insteon failed with their very own Hub Pro. 

I'm wondering if it would be possible to include some code to change the device type of select Insteon devices via the config file. Here are a few examples:

- Keypad Buttons -> By default these get imported as "lights" into HomeKit. I would love to import them as "triggers" instead. I'm not 100% sure if there is a "switch" trigger in HomeKit yet but even just changing it to "motion sensor" would be helpful. That way I could use the button to trigger HomeKit scenes. I could do that with the button being a light as well but the downside is that if I tell Siri "turn on all lights" the button would light up and execute my scene. 

- Define "lights" as "other devices" -> all Insteon DIN modules are automatically imported as lights which is fine most of the time. However, one of my On//Off DIN modules controls my towel heater and I'd like to have a way to configure it as an "outlet" or "heater" instead. That way the towel heater won't accidentally turn on when I ask Siri to turn on the lights. Could be dangerous. 

- Insteon Open/close micro module -> I have a few open/close micro modules that control my window shutters. I haven't imported them into my ISY and Homebridge setup yet but I assume they will show up as lights as well, correct? I would love to be able to define them as "window coverings" like my Lutron blinds. That way when I tell Siri to open all blinds my shutters will open as well. 

These are just three examples but I think it would be extremely helpful if one could call out select devices and assign them a different HomeKit type if need be. Would give users another level of control. 

Is this something you're considering? I have an additional open/close micro module laying around and would be happy to send it to you if you're interested. 

Anyways, keep up the good work. It's really incredible!

**Comment by rodtoll** [comment]
This is something I have considered for a future version. Thank you for your interest and the feature request.

**Comment by rodtoll** [comment]
@VeniceNerd - This is a great idea. Unfortunately I no longer have the time to maintain this plugin so this won't get added. Thank you for your suggestion and for your help. Happy ISYing.
