### ISSUE TITLE
Garage Door Initial Position

### ISSUE THREAD

**Issue by sheazle** [rodtoll/homebridge-isy-js#47]
I have my garage door controlled by an I/O Linc. The Sensor is ON when the door is CLOSED. If I set up that device as a garage door in the JSON, it shows up in Home, but always initializes as OPEN when I start homebridge. how do I tell it to swap the status? I can't open the garage door every time homebridge restarts. it seems to control just fine though, just has the status backwards.

**Comment by rodtoll** [comment]
Under the garage door entry in your config.json file add an alternate: true entry. 

i.e. if your garagedoor entry was this:

           "garageDoors": [
               { "address": "22 31 22 1", "name": "Garage Door", "timeToOpen": 12000 }
           ],

Change it to this:

           "garageDoors": [
               { "address": "22 31 22 1", "name": "Garage Door", "timeToOpen": 12000, alternate: true }
           ],

This will invert the current state logic of the code when dealing with the garage door.
