### ISSUE TITLE
Feature Request: Add capability to use Elk for GD control

### ISSUE THREAD

**Issue by elvisimprsntr** [rodtoll/homebridge-isy-js#50]
Example:

Output 3 = Open/Close momentary relay
Zone 14 = Door status (Violated = Open, Normal = Closed)

**Comment by ndraper** [comment]
I second this feature request. Not only as garage door control but open elk outputs up be able to be many things in home kit.

**Comment by rodtoll** [comment]
@elvisimprsntr , @ndraper - Thank you for your feature request. At this time I am suspending active development so this won't be added.
