### ISSUE TITLE
ISY with Homebridge vs Hub Pro

### ISSUE THREAD

**Issue by TechRemarker** [rodtoll/homebridge-isy-js#51]
Bought an Insteon Hub Pro and several thousands worth of Insteon devices retrofitting all the outlets and switches (40+) and keypads and custom etched labels. The hardware looks great and integrated unlike all the alternatives but with the major benefit of HomeKit support so don't have to use the horrible Insteon+ app.

Started using the moment Apple Home app iOS 10 was in beta and from day one experienced an issue where all the devices said "No Response". For months Insteon wouldn't acknowledge an issue and I assumed it was because iOS 10 was beta. Sadly when it became stable the problem persisted and countless others on the forums confirmed and eventually Insteon admitted it's an issue on their end since 10+ devices requires a special group command by Apple with Insteon still doesn't support.

1. That all said if I buy the top of the line ISY and enable this Homebridge add-on, will I be able to access all the current devices from my Hub Pro in Home App, once I start fresh with ISY? Any known issues in regards to "No Response" with 10+ devices?

2. Insteon Hub supports Sonos through Insteon keypads <http://www.insteon.com/sonos/> but oddly the new Hub Pro does not. Does ISY support Sonos through Insteon keypads?

3. iOS 10.3 now supports programmable keypads for HomeKit scenes. Hub Pro has not mentioned any upcoming support for this. Does ISY and or Homebridge-ISY-JS support this or may in the future?

4. Home app supports a grouping feature which is wonderful since you can group say three way switches to appear as one device in home app, thus if I say set kitchen to 50% it can update all the 3 switches that control that light and update the status lights on them as well because I have them all linked to each other. Since that all works with Hub Pro and HomeKit, is there any known issue accomplishing the same with ISY and Homebridge-ISY.

5. In general, color connected light bulbs (such as Lifx and Hue) aren't compatible with Insteon/regular switches because turning off a connected bulb or dimming it will cause them to not work. Lutron is closest with <http://www.lutron.com/en-US/Products/Pages/Components/ConnectedBulbRemoteControl/Overview.aspx> but no HomeKit support. My question is, with ISY and an Insteon Dimmable Switch, can the switch be programmed so when you turn the switch off it doesn't cut power but instead sends a signal to lifx to turn the light on, and when dimming rather than reducing power send a signal to lifx to dim? 

6. ISY Mac app? From all my googling of ISY all the images seem to show an 90s style windows app. Does anyone have screenshots of the current day Web app (or Mac app).

Not sure if this is the right place to be asking these questions, so any advice or thoughts on any would be greatly appreciated. Thank you!

**Comment by respectTheCode** [comment]
I have looked for the same thing and found that it does not exist. Most of what you are asking for can be accomplished with [Home Assistant](https://home-assistant.io) but it will take some work to setup and maintain. There is also a homebridge plugin for Home Assistant. I haven't tried it with an INSTEON Hub but it is supported.

The ISY comes with a Java app that works most of the time on Mac. I run it in a Windows VM because I have found it to be more reliable. It still has the same 90s style UI. I have asked about it on the official forums and the devs don't recognize the bad UI or even the Mac as a platform they should care about. All of that said the ISY is the best hardware solution out there for INSTEON that I have found.

The hombridge ISY plugin does seem to work better than the Home Assistant plugin but that could just be a configuration problem.

**Comment by TechRemarker** [comment]
Thanks so much for sharing your thoughts. 

While the ISY app is an ugly as can be and having to use a java app in 2017 on Mac, rather than a clean modern web app does sound a bit archaic. But I understand that many good developers don't understand the importance of good design. So in this case would rather horrible design for reliable platform, since I'd presumably have to only set it up once, and then just use the Home App and Siri for then on.

Continued researching and saw a thread on someone who had supposedly got Sonos working with ISY, so will have to verify.

For Home Assistant just reviewed their site and while looks much better on the surface than ISY, not sure if that would be a fit for me. As I have all my other autmations working great with Home app and native HomeKit devices, and the only issue is with Insteon Switches (dimmer and on/off), Insteon Outlets (dimmer and on/off), Insteon 6/8 keypads (dimmer and.on/off), and Insteon battery dimmer switches). Since while they all work with Hub Pro and HomeKit, they No Response issue in the home app is incredibly frustrating even though technically Siri and all the automations work as desired.

With Home Assistant, it says Insteon Hub support was disabled last year by requests of Insteon, but Home Assistant was polling devices every 30 seconds rather than using the proper streaming api. Hard to tell if it was ever resolved as still shows as disabled. 

Going to keep researching to see what the best option is. Such as 1) wait another year or two for Insteon to finally release a firmware update to fix the No Response issue. 2) Setup ISY with Homebridge which supposedly will match the Hub Pro features but also fix the No Response issue or 3) Try Insteon Hub (not pro) and search for a homebridge plugin that may avoid the no response issue and then Sonos would potentially work as well and avoid having to use the old ISY interface.

Thank you for your help.

**Comment by macjeff** [comment]
I use ISY with homebridge.   Took a lot of time to exclude devices and add the scenes I want but works great.

I can tell you that Universal-Devices is a homebridge fan and are doing things in Alpha that will make it better in the future.  Even I don’t know what they are but they plan to support it even better (maybe an official plugin)

Jeff

**Comment by TechRemarker** [comment]
@macjeff Thanks sharing your experience with ISY. Spending a lot of time in setup isn't a concern at all for me, as with Insteon Hub I've spent nearly a year, and countless times resetting all my devices re-adding all 40+ and recustomizing, each time trying to isolate variables in hoping to get to the bottom of the No Response issue. Until Insteon eventually admitted it was infacft on their end and currently no timeline or promise of a future fix in regards to people with more than 10+ devices on Insteon Hub Pro. 

My thing is, if I'm going to spend that additional money (on the ISY) and countless hours setting it up to perfection, want to make sure it will resolve my particular issues with the Insteon Hub Pro limitations. Such as making sure No Response status isn't an issue (sounds like it is not), that grouping 3 ways and keeping that all in sync will work as I have it currently with combination of HomeKit and Insteon Hub Pro, that I can program Insteon Keypads to work with Sonos like Insteon Hub (non pro) can (heard somewhere got this working but not sure), if ISY supports or will supports Homekits new support for programming keypads to HomeKit scenes, etc.

Ultimately will have to bite the bullet and try to be sure, but hoping to do as much research as possible first to see what definitely will or won't work based on others past experiences. As right now our system works in general very well (other than No Response status, etc). And before I subject the family to a few days, weeks etc of things not working at all, want to make sure I can promise it's worth it if they just wait a bit. Once again appreciate all the advice of people who have used Homebridge and ISY.

**Comment by PaulWieland** [comment]
I am currently using an ISY with around 3 dozen insteon devices. I am also a mac only household.

I wont repeat what others have said, other than to re-affirm that UDI is tone deaf when it comes to native support for iOS.


1. That all said if I buy the top of the line ISY and enable this Homebridge add-on, will I be able to access all the current devices from my Hub Pro in Home App, once I start fresh with ISY? Any known issues in regards to "No Response" with 10+ devices? 
    * Yes it will work just fine. I have around 3 dozen insteon devices + ISY + appleTV + mac mini running homebridge and I have had pretty good success (not flawless, but 99% great).

2. Insteon Hub supports Sonos through Insteon keypads http://www.insteon.com/sonos/ but oddly the new Hub Pro does not. Does ISY support Sonos through Insteon keypads?
    * Have a look at this post: http://forum.universal-devices.com/topic/11716-insteon-and-sonos-with-isy-994i/

3. iOS 10.3 now supports programmable keypads for HomeKit scenes. Hub Pro has not mentioned any upcoming support for this. Does ISY and or Homebridge-ISY-JS support this or may in the future?
    * With this Homebridge plugin, each button on the keypad can be presented to iOS as a unique switch. The better approach I have found though is to setup an Insteon/ISY scene that has the button + load bearing device in it, then configure homebridge to see that scene and hide the button & load device.

4. Home app supports a grouping feature which is wonderful since you can group say three way switches to appear as one device in home app, thus if I say set kitchen to 50% it can update all the 3 switches that control that light and update the status lights on them as well because I have them all linked to each other. Since that all works with Hub Pro and HomeKit, is there any known issue accomplishing the same with ISY and Homebridge-ISY.
    * This is a limitation of insteon that @rodtoll and I have discussed a number of times. UDI refuses to address this even though they could. See here: https://github.com/rodtoll/homebridge-isy-js/issues/21

5. In general, color connected light bulbs (such as Lifx and Hue) aren't compatible with Insteon/regular switches because turning off a connected bulb or dimming it will cause them to not work. Lutron is closest with http://www.lutron.com/en-US/Products/Pages/Components/ConnectedBulbRemoteControl/Overview.aspx but no HomeKit support. My question is, with ISY and an Insteon Dimmable Switch, can the switch be programmed so when you turn the switch off it doesn't cut power but instead sends a signal to lifx to turn the light on, and when dimming rather than reducing power send a signal to lifx to dim?
    * These kinds of devices should not be physically connected to any load controlling insteon device (Switch or outlet). Instead you need to control them with a virtual switch (keypad or switch that has nothing wired to it's load). It doesn't look like UDI has provided native support for Hue yet, but you could write your own node.js script to act as a bridge between homebridge and hue so you can control these devices with an insteon keypad. I have done something very similar where a keypad button is turning off my home entertainment center via a network connected infrared flasher.

6. ISY Mac app? From all my googling of ISY all the images seem to show an 90s style windows app. Does anyone have screenshots of the current day Web app (or Mac app).
    * UDI's attitude toward this makes me not want to buy their product, but unfortunately it's the best there is for Insteon at the moment.

**Comment by macjeff** [comment]
I can answer #6.  

They have a config app.  Its not pretty but it does the job.

They have a  dashboard web app (java) which is a lot prettier BUT that is not what the ISY apps are meant for.   

There are 3rd party apps (even on the app store for mac and app store for IOS) to support the ISY.

And the ISY fully supports Alexa.  You can even have the spoken name different.   So you can call your garage Garage Door 1 and Garage Door 2 in the ISY but when you ask Alexa you said Jeff’s Garage.  You can have up to 5 spoken words so you could even call it Jeff’s garage one day and Jeff’s car storage the other.

And it is about to fully support Google Home.

I love the ISy.   I have tried Wink, SmartThings, Insteon Hub.    ISY beats them all.

Jeff

**Comment by TechRemarker** [comment]
@fahrvergnuugen that response is incredibly helpful!

I actually found that Sonos link this morning (after submitting my original post here). Which looks relatively promising though appears a bit dated but also certainly promising which is great.

For #4, in regards to an Insteon limitation, wanted to note I do have this working very well with Insteon Hub Pro and Homkit currently. Since that linked discussion appears to be about changing status/dimming of a "Scene" rather than a HomeKit Group. That is HomeKit of course has Scenes, which is originally what I tried to do. That is putting 3 switches into a scene to and other methods to control them as one since Insteon's app didn't have a method to deal with it.

Then I discovered a less often discussed feature unique to Home app which is Grouping. So normally if I had a Living Room Ceiling Light and 3 switches that control it I would have 3 devices in Home App "Living Room Ceiling 1", "Living Room Ceiling 2", and "Living Room Ceiling 3". What I then do in Home app is select two of them and choose, "Group with Other Accessories..." which then allows me to merge those three devices into one device simply called, "Living Room Ceiling". So then I can simply use Siri or Home app to turn that three way on/off or dim to any level. And since the three ways are hard linked to each other all the status leds stay in sync. And If I say set Living Room Ceiling to 50% via Siri, all three of the switches LEDS immediately update to reflect that. 

So in my experience, all of that works perfectly, as long as you use Home App Grouping to initially setup (since not possible if just using Insteon+ app). Just wanted to make sure that will still work on ISY as it does on Hub Pro. I'm thinking it will since its more Home that is doing the fun stuff.

As a side note, while Home supports Grouping where Insteon app does not, Insteon app does support Zones, meaning I can assign "Rooms" to "Zones" such as rooms to "First Floor" or "Second Floor" which I wish Home app had. Home app has Rooms and Scenes and Groups but no concept of Zones. Using Grouping for Zones wouldn't make sense, nor using Rooms as a Zone. But hopefully eventually Home will support Zones as well.

**Comment by PaulWieland** [comment]
@ChrisChiera It's funny, Zones (e.g. first floor, second floor, outside, etc) used to be part of homekit, but it looks like apple removed them. The grouping feature you mentioned does seem to be a solution for the dimmable scene option - thanks for the tip! I think it's something Apple added to homekit after I ran into this problem. I'll have to revisit it now...

**Comment by rodtoll** [comment]
This is a very interesting and very thoughtful discussion -- although not really a homebridge-isy-js issue discussion. Closing as part of cleanup.
