### ISSUE TITLE
Expose on/off buttons to Home app for scenes?

### ISSUE THREAD

**Issue by TechRemarker** [rodtoll/homebridge-isy-js#58]
For anyone who may still is monitoring this repo, I have a question.

On 6 and 8 scene Insteon scene keypads, all the scene buttons are exposed to Home app on the iPhone except the load buttons, so for 6 buttons the top and bottom, and for 8 the top left.

I'd like to reprogram those to a scene that way when using them they will turn a HomeKit light off/on via software rather than cutting actual power. In the past I thought this wasn't possible but insteon says the power buttons can be reprogrammed to a scene. I'm looking into that now, but assuming that does work, that would only let me reprogram to an insteon scene, and not a HomeKit scene, so still need a way to expose those buttons in Home app like all the other buttons.

Does anyone know how to do this?

**Comment by PaulWieland** [comment]
I was unaware that you could decouple the load from the main button - do you have a link to the instructions on how to do that?

That being said, if you _can_ decouple the load from the button, then you should be able to set it up just like any other button on the keypad (make a scene with only the button in it, then include that scene in your isy homebridge config).

**Comment by TechRemarker** [comment]
I also was unaware, as could have sworn last time I asked Insteon support a year or 2 ago, that said it wasn't possible but as of last week, they said via support it was, but they haven't yet described the process as they recommended I call since they alluded was little more complicated. Thanks for your help.
