### ISSUE TITLE
Designate an I/O Linc as a Garage Door Opener

### ISSUE THREAD

**Issue by PaulWieland** [rodtoll/homebridge-isy-js#6]
It seems that there is a specific Accessory type in HomeKit for Garage doors (Its also defined in `hap-nodejs/accessories/GarageDoorOpener_accessory.js`. If you say "Siri, open the garage door" she responds with "I wasn't able to find any garage doors".

Of course an I/O Linc can be used for a lot of different purposes, but probably the most common one is to control a garage door. I was thinking that having an object in the config similar to "ignoreDevices" called "myGarageDoors" which would allow you to designate a specific IOLinc as a garage door.

**Comment by PaulWieland** [comment]
I also just noticed that  only the contact sensor is showing up in HomeKit. The relay control is missing.

**Comment by respectTheCode** [comment]
This would be great.

I use a state plus a couple of programs to control my garage door since the ISY treats the sensor and the relay as 2 nodes instead of 1.

**Comment by PaulWieland** [comment]
@respectTheCode This is slightly off topic, but I have two keypads + an I/O Linc setup and have complete control of my garage door using standard Insteon Scenes without the need of any ISY programs. The keypad buttons light up when the door is open (they are responders to the I/O Linc sensor). The buttons are controllers of the I/O Linc relay.

For some reason though, the I/O Linc's relay is not showing up in ISY-JS. Only the sensor shows up. 
Does yours work?

**Comment by Chioti** [comment]
I do not have an ISY device yet, just an Insteon HUB.  I am considering switching to the ISY if this plugin supports:
1. Status of Lights/Outlets
2. I/O Lync as Garage Door Opener with sensor support.

Can anyone comment on #1 and can @rodtoll please comment on whether #2 will be implemented?

Thanks

**Comment by rodtoll** [comment]
1. Yes. If you turn on and off your lights external to the plug-in.
   (i.e. use the ISY or just go to the switch and switch it). Then the plugin
   will see this and update the state in Homekit.
2. The plugin will expose the I/O linc as two separate devices -- a
   switch for the relay and the sensor as a door window contact sensor. I have
   not implemented the garage door contract although it is on my worklist for
   January.

**Comment by rodtoll** [comment]
@fahrvergnuugen , @SteliosMakrinos - Garage door support through an I/O Linc device is now supported. See the README.md.
