### ISSUE TITLE
"Turn off Fan" results in exception

### ISSUE THREAD

**Issue by abailey22** [rodtoll/homebridge-isy-js#7]
When issuing the command to Siri to turn off the fan it causes the following exception. Please let me know if you need anymore information.  Even using MyTouchHome to turn off the fan results in the same exception. 

assert.js:89
  throw new assert.AssertionError({
  ^
AssertionError: Unexpected fan level: undefined
    at ISYFanDevice.ISYBaseDevice.sendFanCommand (/usr/local/lib/node_modules/homebridge-isy-js/node_modules/isy-js/isydevice.js:156:9)
    at ISYFanAccessory.setFanRotationSpeed (/usr/local/lib/node_modules/homebridge-isy-js/index.js:245:15)
    at ISYFanAccessory.setFanOnState (/usr/local/lib/node_modules/homebridge-isy-js/index.js:270:9)
    at emitThree (events.js:97:13)
    at emit (events.js:175:7)
    at Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:152:10)
    at Bridge.Accessory._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:516:22)
    at emitThree (events.js:97:13)
    at HAPServer.emit (events.js:175:7)
    at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:682:10)

**Comment by rodtoll** [comment]
Good news on this. Last night I published version 0.0.5 of the package which included a fix for this issue. If you update to the latest this should be resolved.

**Comment by rodtoll** [comment]
Let me know if you have version 0.0.5 of the package. If you do and it's still happening then it will be a different problem. And I'll need to know what sequence of commands you sent -- i.e. set fan to high, then turned it off then to low or something.

**Comment by abailey22** [comment]
@rodtoll - It appears that version 0.0.5 was not published to NPM. Is this correct, Should I install from git?

**Comment by rodtoll** [comment]
@abailey22 I just double checked and homebridge-isy-js is currently published as 0.0.5. I tested by creating a temp application and doing an install:

MBP:tmp rodtoll$ npm install homebridge-isy-js
{"node":"0.10.31","npm":"1.4.23"})
homebridge-isy-js@0.0.5 node_modules/homebridge-isy-js
├── xmldoc@0.4.0 (sax@1.1.4)
├── faye-websocket@0.10.0 (websocket-driver@0.6.3)
└── restler@3.4.0 (yaml@0.2.3, qs@1.2.0, iconv-lite@0.2.11, xml2js@0.4.0)

I then checked the source to make sure it was up to date. 

I also checked the npmjs.com website entry:

https://www.npmjs.com/package/homebridge-isy-js
-->
rodtoll rodtoll published yesterday
0.0.5 is the latest of 4 releases
github.com/rodtoll/homebridge-isy-js
MIT license

And double checked the npm data:

$ npm show homebridge-isy-js

{ name: 'homebridge-isy-js',
  description: 'Homebridge plugin for ISY series of home controllers from universal devices ',
  'dist-tags': { latest: '0.0.5' },
  versions: [ '0.0.1', '0.0.2', '0.0.4', '0.0.5' ],
  maintainers: 'rodtoll rod_toll@...',
...

Did you do an npm update homebridge-isy-js -g to update your global install? Could you be working against a mirror that's not updated yet?

The way to tell if you have v0.0.5 is to look at the index.js file and see if this line is present index index.js (new):
if(fanSpeed == this.device.FAN_OFF) {
Or the old broken code:
if(fanSpeed == this.device.FAN_LEVEL_OFF) {

Hope this helps!

**Comment by abailey22** [comment]
Thanks @rodtoll, I ran the npm update again last night and I got version 0.0.7. Fan control works great in there. I did try running "npm-check" and it did detect the new version 0.0.7 but it didn't pickup 0.0.5 as well. I'm running homebridge on an RP2. Thanks again!
