### ISSUE TITLE
Insteon Venstar Thermostat support?

### ISSUE THREAD

**Issue by ficklma1** [rodtoll/homebridge-isy-js#8]
Is there support for Insteon Venstar Thermostat?  For some reason these do not show up in homebridge as a device.  If they aren't currently supported, is it possible to support?
Thanks!

**Comment by ficklma1** [comment]
Any way to get these thermostats working through this interface?

**Comment by rodtoll** [comment]
At the moment there isn't. The thermostat has a very deep set of
capabilities and properties specific to it. It would be new code and
actions. This is challenging given I don't have one.

If there is some documentation of the properties I might be able to
prototype something if someone could test it.

If you visit http://<your isy address>/rest/nodes with your browser and
send me the node entry for the thermostat I might be able to at least do a
read-only view and prototype the actions.

**Comment by ficklma1** [comment]
Thanks @rodtoll
Here's my node entry for my first floor Venstar Thermostat module.

[isy-venstar.txt](https://github.com/rodtoll/homebridge-isy-js/files/105610/isy-venstar.txt)

**Comment by ficklma1** [comment]
Was the attachment all you needed in order to investigate this?  Hopefully this will give you enough information in order to pursue implementing these thermostats.

**Comment by ficklma1** [comment]
@rodtoll 
Is there any possibility to check on the ISY thermostat functionality?

**Comment by rodtoll** [comment]
@ficklma1 - Unfortunately it looks like this will be a bigger job then I thought. I actually have a venstar thermostat now but I was hoping I could get it to work without wiring it to my actual furnace (I have a NEST and don't want to switch) but I was unsuccessful. Plus the thermostat device types are unique in that they require multiple types of state whereas all other devices just have one state so I need to do some refactoring. I'm still experimenting. If I can get it wired up I can do some testing and build an emulator so I can build support in. So no ETA yet but I've had a few requests. It will be weeks likely.

**Comment by ficklma1** [comment]
@rodtoll - Any progress on the Insteon Thermostats?

**Comment by rodtoll** [comment]
@ficklma1 - Very little progress. The problem is I need one of these devices to actually test this -- and one which is wired up to an actual furnace. The devices use multiple types of state and accept commands which are different from every other type of device. I'm going to need a contributor to submit an implementation. Adding to the README.md to highlight the need.

**Comment by joeoates** [comment]
What about support for the newer Insteon wired thermostats (2441TH)?
http://www.smarthome.com/insteon-2441th-thermostat.html
Are these simnifically different from the Venstar Insteon devices?

**Comment by ficklma1** [comment]
@rodtoll - Has there been any more news or possibilities to implement Insteon/ISY Thermostats?

**Comment by magus424** [comment]
I'm currently using homebridge-isy-js and just installed a Venstar thermostat; I'll be looking into it once I have it paired properly.

**Comment by ficklma1** [comment]
@magus424 - just checking in to see if you were able to pair it and make any progress.

**Comment by magus424** [comment]
Not yet, I've got family in town from the holidays so I haven't even had time to program it the old fashioned way yet :)  I'll update when I have more to report (or questions for @rodtoll) ;)

**Comment by magus424** [comment]
I've got it paired with the ISY now, but he wasn't kidding about the multiple states and available commands :)

@rodtoll - do you have any code from when you were initially looking at it that I might be able to see as a starting point? It's looking like I'd have to add support to isy-js first, is that correct?

**Comment by ficklma1** [comment]
@magus424 @rodtoll any updates on this?
Just checking in again.  Any thoughts how this could move forward?

**Comment by flmmkr1** [comment]
I don't have a Venstar thermostat, just a regular Insteon wired thermostat. I just got Homebridge working with my ISY. I'd love to get the thermostat working. It's the only thing that's not. Please let me know if I can help in anyway. I have no programming experience, but am willing to help and do whatever I can. Just give me step-by-step instructions on what to do. Running my Homebridge on a Raspberry Pi 3 B with Raspbian Jessie Lite. I'm using the ISY994izw. I also have a Insteon Hub 2 and Hub Pro that are currently disconnected. Main computer is a MacBook Pro with Sierra. I'm SSH'ing into my Homebridge.

**Comment by rodtoll** [comment]
@ficklma1 - I am discontinuing support for the plugin so I won't be able to add support for the venstar thermostat. To truly support it will not be trivial as it has different actions and different properties then other devices -- but it is possible if someone has the time. Thank you for your interest.
