### ISSUE TITLE
Last changed characteristic?

### ISSUE THREAD

**Issue by PaulWieland** [rodtoll/homebridge-isy-js#9]
Would it be possible to add a "last changed" or "last event" characteristic that contained a timestamp?

It would be nice to be able to see when the last time a motion sensor was tripped for example. 

I also have an isy-js program im working on that will pan my ptz camera and start recording when motion is detected in the driveway, but i want to ignore the event if i pressed my "im leaving home" keypad button within the last 2 minutes.

**Comment by rodtoll** [comment]
Are you looking for that in the homebridge plugin or in the isy-js library underneath?

The homebridge plugin can only export characteristics that are supported by homekit and unfortunately this is not one of the supported ones. But I could certainly see this getting added to the isy-js library. Opening an issue there to track and closing this one.

Here is the isy-js issue:
https://github.com/rodtoll/isy-js/issues/16

**Comment by PaulWieland** [comment]
@rodtoll I was actually hoping for both, but that's because I did not realize that you couldn't add arbitrary characteristics to accessories. Based on some of the other homebridge plugins that I have looked at, I thought you could define any characteristic that you want (like "volume" for example, even though HomeKit doesn't have an out of the box Audio/Video Accessory).

**Comment by rodtoll** [comment]
Hmm. I wasn't aware of that. If you can point me at a plugin which does a custom attribute I can see about adding it. Do the usual HomeKit apps expose these custom attributes?

**Comment by PaulWieland** [comment]
[Here's one example](https://github.com/neonightmare/homebridge-yamaha/blob/master/index.js#L97)

I wish I had more time to unravel and experiment with it. I don't have a Yamaha receiver, but I want to try something similar with my globalcache homebridge plugin for my AV system. I was hoping I could get homekit app control over volume up/down, mute, input, power on & off.

**Comment by rodtoll** [comment]
@fahrvergnuugen - I've added the property to the base isy-js library with 0.3.7. It's called lastChanged and should be available on all device types. Will look into adding it to the homekit platform sometime soon.

**Comment by PaulWieland** [comment]
Awesome, will try it out later today. Thanks!
